backend:
  name: github
  repo: visyond/website-hugo
  base_url: https://cms.visyond.com

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "solutions"
    label: "Solutions" 
    folder: "site/content/solutions"
    create: true
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Menu", name: "menu", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "casestudy"
    label: "Case Study"
    folder: "site/content/casestudy"
    create: true
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Tooltip", name: tooltip, widget: list, fields: [{label: Heading, name: title, widget: string}], required: false}
      - {label: "Client image", name: "client", widget: "image", required: false}
      - {label: "Client asked", name: "client_ask", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Widget aside", name: aside, widget: list, fields: [{label: Heading, name: "content", widget: "markdown"}], required: false}
      - {label: "First solution", name: "first_solution", widget: "markdown", required: false}
      - {label: "Second solution", name: "second_solution", widget: "markdown", required: false}
      - {label: "Third solution", name: "third_solution", widget: "markdown", required: false}
  
  - name: "landings"
    label: "Landings"
    folder: "site/content/landings"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Top image", name: "topImage", widget: "image", required: true }
      - { label: "Top description", name: "descr", widget: "string", required: false }
      - { label: "Video title", name: "videoTitle", widget: "string", required: false }
      - { label: "Video descr", name: "videoDescr", widget: "string", required: false }
      
      - { label: "Video url", name: "popupUrl", widget: "string", required: false }      
      - { label: "Trusted by", name: "trusted", widget: "list",
        fields: [
          {label: "logo", name: "logo", widget: "image"}
        ],
        required: false,
      }

      - { label: "Feature title", name: "featureTitle", widget: "string", required: true }      
      - { label: "Features", name: "feature", widget: "list",
        fields: [
          {label: "Description", name: "content", widget: "string"},
          {label: "Icon", name: "ico", widget: "image"}
        ],
        required: false,
      }
      - { label: "How to photo", name: "howToPhoto", widget: "image" }
      - { label: "How to text", name: "howTo", widget: "markdown", required: false }
      - { label: "How to company", name: "howToCompany", widget: "markdown", required: false }

      - { label: "Case study", name: "case", widget: "list",
        fields: [
          {label: "Case study link", name: "caseLink", widget: "string"},
          {label: "Icon", name: "caseIco", widget: "image"},
          {label: "Case study description", name: "caseDescr", widget: "string"},
        ],
        required: false,
      }
      - { label: "Challenge and Solutions", name: "challenge", widget: "list",
        fields: [
          {label: "Challenge link", name: "caseLink", widget: "string"},
          {label: "Icon", name: "caseIco", widget: "image"},
          {label: "Challenge description", name: "caseDescr", widget: "string"},
        ],
        required: false,
      }
      - { label: "Features", name: "features", widget: "list",
        fields: [
          {label: "Image", name: "featureImg", widget: "image"},
          {label: "Title", name: "title", widget: "string"},
          {label: "Description", name: "descr", widget: "string"},
          {label: "Link description", name: "linkDescr", widget: "string"},
          {label: "Link path", name: "linkPath", widget: "string"},
        ],
        required: false,
      }
      - { label: "Featured Hover", name: "featured", widget: "list",
        fields: [
          {label: "Logo", name: "logo", widget: "image"},
          {label: "Description", name: "descr", widget: "string"},
        ],
        required: false,
      }
      - { label: "Pricing title", name: "pricingTitle", widget: "string", required: true }
      - { label: "Pricing sub-title-1", name: "firstPricingSubTitle", widget: "string", required: true }
      - { label: "Pricing sub-title-2", name: "secondPricingSubTitle", widget: "string", required: true }

      - { label: "Left card title", name: "leftCardTitle", widget: "string", required: true }
      - { label: "Left card sub-title", name: "leftCardSubTitle", widget: "string", required: true }
      - { label: "Left card content", name: "leftCardSubContent", widget: "markdown", required: true }
      
      - { label: "Middle card title", name: "middleCardTitle", widget: "string", required: true }
      - { label: "middle card sub-title", name: "middleCardSubTitle", widget: "string", required: true }
      - { label: "middle card content", name: "middleCardSubContent", widget: "markdown", required: true }
      
      - { label: "Right card title", name: "rightCardTitle", widget: "string", required: true }
      - { label: "Right card sub-title", name: "rightCardSubTitle", widget: "string", required: true }
      - { label: "Right card content", name: "rightCardSubContent", widget: "markdown", required: true }
      

  # - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
  #   label: "Post" # Used in the UI, ie.: "New Post"
  #   folder: "site/content/post" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   fields: # The fields each document in this collection have
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Intro Blurb", name: "description", widget: "text"}
  #     - {label: "Image", name: "image", widget: "image", required: false}
  #     - {label: "Body", name: "body", widget: "markdown"}
  - name: "simplepages"
    label: "Simplepages"
    folder: "site/content/simplepages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      # - {label: Type, name: type, widget: hidden, default: simplepages}
      # - {label: Page, name: page, widget: hidden, default: "/simplepages.html"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # - name: "custom" # Used in routes, ie.: /admin/collections/:slug/edit
  #   label: "Custom Page" # Used in the UI, ie.: "New Post"
  #   folder: "site/content/page" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   fields: # The fields each document in this collection have
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Intro Blurb", name: "description", widget: "text"}
  #     - {label: "Image", name: "image", widget: "image", required: false}
  #     - {label: "Body", name: "body", widget: "markdown"}

  - name: "products"
    label: "Pages"
    files:
      # - file: "site/content/products.md"
      #   label: "Products Page"
      #   name: "products"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Type, name: type, widget: hidden, default: products}
      #     - {label: Page, name: page, widget: hidden, default: "/products.html"}
      #     - {label: Image, name: image, widget: image}
      #     - {label: Heading, name: heading, widget: string}
      #     - {label: Description, name: description, widget: string}
      #     - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      #     - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      #     - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      #     - {label: Full_image, name: full_image, widget: image}
      #     - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/contact.md"
        label: "Contacts page"
        name: "contact"
        fields:
          - { label: Type, name: type, widget: hidden, default: contact }
          - { label: Contact, name: contact, widget: hidden, default: "/contact.html" }
          - { label: Title, name: title, widget: string }
          - { label: "Top image", name: topImage, widget: "image" }
          - { label: Mail, name: mail, widget: string }
          - { label: Social, name: contactsSocial, widget: list, fields: [
            { label: "Icon", name: socialIcon, widget: "image" },
            { label: "Link", name: socialLink, widget: "string" }
          ]}
          - { label: Phone, name: contactsPhone, widget: list, fields: [
            { label: "number", name: socialPhone, widget: "string" }
          ]}
          - { label: Email, name: contactsEmail, widget: list, fields: [
            { label: "email", name: socialEmail, widget: "string" }
          ]}
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields: 
          - { label: Cards, name: "cards", widget: list, fields: [
              { label: "Card title", name: "cardTitle", widget: "string" },
              { label: "Card background", name: "cardBackground", widget: "image" },
              { label: "Card icon", name: "cardIcon", widget: "image" },
              { label: "Card description", name: "cardDescr", widget: "string" },
              { label: "Card path", name: "cardLink", widget: "string" },
          ]}
          - { label: "Clients", name: "client", widget: list, fields: [
            { label: "Client icon", name: "clientIcon", widget: image }
          ]}
          - { label: Slider, name: "slider", widget: list, fields: [
              { label: "slider photo", name: "sliderphoto", widget: "image" },
              { label: "slider description", name: "sliderDescr", widget: "string" },
              { label: "slider company", name: "slidercompany", widget: "string" },
              { label: "slider logo", name: "sliderlogo", widget: "image" },
          ]}
