version: "3.0"
services:
  cms:
    container_name: cms
    image: visyond/visyond-cms:latest
    restart: unless-stopped
    volumes:
      - /etc/nginx/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - 80:80
    networks:
      - visyond-net
networks:
  visyond-net:
    name: visyond-net
