version: "3.0"
services:
  cms:
    container_name: cms
    image: visyond/visyond-cms:latest
    ports:
      - 80:80
    networks:
      - visyond-net
networks:
  visyond-net:
    name: visyond-net
