name: CI Pipeline For Visyond CMS

on:
  push:
    branches: [ feature/op-staging ]
  pull_request:
    branches: [ feature/op-staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        env:
          GITHUB_SHA_SHORT: ${GITHUB_SHA::6}
        uses: docker/build-push-action@v3
        with:
          file: docker/Dockerfile
          push: false
          tags: visyond/visyond-cms:latest,visyond/visyond-cms:${{ GITHUB_SHA_SHORT }}
