name: CI Pipeline For Visyond CMS

on:
  push:
    branches: [ feature/op-staging ]
  pull_request:
    branches: [ feature/op-staging ]

jobs:
#   build-arti:
#     runs-on: macos-12
#     steps:
#       -
#         name: Checkout
#         uses: actions/checkout@v3

#       - name: Use Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '10'
#       - 
#         name: Install dependencies and run build the app
#         run: |
#           npm install
#           npm run build
       
#       - 
#         name: Temporarily save build folder
#         uses: actions/upload-artifact@v3
#         with:
#           name: build-artifact
#           path: dist
#           retention-days: 1

  build-img:
    runs-on: ubuntu-latest
#    needs: build-arti
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Retrieve saved build folder
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: dist
      -
        name: Create docker image
        run: |
          bash docker-build.sh ${{ secrets.REGISTRY_USER }} ${{ secrets.REGISTRY_PASSWORD }}
