name: CI Pipeline For Visyond CMS

on:
  push:
    branches: [ feature/op-staging ]
  pull_request:
    branches: [ feature/op-staging ]

jobs:
  build:
    runs-on: ubuntu-latest
#    env:
#      GIT_KEY:
    steps:
      -
        name: Build and push
        run: |
          echo "Github SHA: ${GITHUB_SHA::6}"
