name: CI Pipeline For Visyond CMS

on:
  push:
    branches: [ feature/op-staging ]
  pull_request:
    branches: [ feature/op-staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: visyond/visyond:$GITHUB_SHA
    steps:
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: docker/Dockerfile
          push: false
          tags: ${{ env.TAG }}
