name: CI Pipeline For Visyond CMS

on:
  push:
    branches: [ feature/op-staging ]
  pull_request:
    branches: [ feature/op-staging ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Create docker image
        run: |
          bash docker-build.sh ${{ secrets.REGISTRY_USER }} ${{ secrets.REGISTRY_PASSWORD }}
